name: Dependency Injection Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/MyLib.DependencyInjectionExtensions/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/MyLib.DependencyInjectionExtensions/**'

jobs:
  DependencyInjection-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: src/MyLib.DependencyInjectionExtensions
        run: dotnet restore
      - name: Build
        working-directory: src/MyLib.DependencyInjectionExtensions
        run: dotnet build --no-restore