name: Abstractions Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/MyLib.Abstractions/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/MyLib.Abstractions/**'

jobs:
  Abstractions-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: src/MyLib.Abstractions
        run: dotnet restore
      - name: Build
        working-directory: src/MyLib.Abstractions
        run: dotnet build --no-restore