name: MyLib Abstractions Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: src/MyLib.Abstractions
      run: dotnet restore
    - name: Build
      working-directory: src/MyLib.Abstractions
      run: dotnet build --no-restore
